[server]
model = "Qwen/Qwen3.5-0.8B"
host = "0.0.0.0"
port = 30000

[server.args]
load_format = "dummy"
skip_server_warmup = true
disable_cuda_graph = true

[env]

[bench]
dataset_name = "random"
num_prompts = 30
request_rate = 1
random_input_len = 128
random_output_len = 4
warmup_requests = 1
